// Restaurants
export const RESTAURANT_FOOD_CHANGE = 'RESTAURANT_FOOD_CHANGE'
export const RESTAURANT_LOCATION_CHANGE = 'RESTAURANT_LOCATION_CHANGE'
export const RESTAURANT_YELP_SEARCH_START = 'RESTAURANT_YELP_SEARCH_START'
export const RESTAURANT_YELP_SEARCH_SUCCESS = 'RESTAURANT_YELP_SEARCH_SUCCESS'
export const RESTAURANT_YELP_SEARCH_FAIL = 'RESTAURANT_YELP_SEARCH_FAIL'
export const RESTAURANT_GOOGLE_SEARCH_START = 'RESTAURANT_GOOGLE_SEARCH_START'
export const RESTAURANT_GOOGLE_SEARCH_SUCCESS = 'RESTAURANT_GOOGLE_SEARCH_SUCCESS'
export const RESTAURANT_GOOGLE_SEARCH_FAIL = 'RESTAURANT_GOOGLE_SEARCH_FAIL'

// Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
