// Restaurants
export const RESTAURANT_INPUT_CHANGE = 'RESTAURANT_INPUT_CHANGE';
export const RESTAURANT_GOOGLE_SEARCH_START = 'RESTAURANT_GOOGLE_SEARCH_START';
export const RESTAURANT_GOOGLE_SEARCH_SUCCESS =
  'RESTAURANT_GOOGLE_SEARCH_SUCCESS';
export const RESTAURANT_GOOGLE_SEARCH_FAIL = 'RESTAURANT_GOOGLE_SEARCH_FAIL';
export const RESTAURANT_REQUESTING_LOCATION = 'RESTAURANT_REQUESTING_LOCATION';

// Auth
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAIL = 'AUTH_LOGOUT_FAIL';

// User
export const USER_GET_INFO_START = 'USER_GET_INFO_START';
export const USER_GET_INFO_SUCCESS = 'USER_GET_INFO_SUCCESS';
export const USER_GET_INFO_FAIL = 'USER_GET_INFO_FAIL';
export const USER_GET_PLACES_SUCCESS = 'USER_GET_PLACES_SUCCESS';
export const USER_POST_INFO_START = 'USER_POST_INFO_START';
export const USER_POST_INFO_SUCCESS = 'USER_POST_INFO_SUCCESS';
export const USER_POST_INFO_FAIL = 'USER_POST_INFO_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_CLOSE_EDIT = 'USER_CLOSE_EDIT';

// App
export const GEO_START = 'GEO_START';
export const GEO_SUCCESS = 'GEO_SUCCESS';
export const GEO_FAIL = 'GEO_FAIL';
export const TOGGLE_GEO_LOC_PERM = 'TOGGLE_GEO_LOC_PERM';
export const SET_REDIRECT_PARENT = 'SET_REDIRECT_PARENT';

// Home
export const HOME_POST_YOUR_PLACES_START = 'HOME_POST_YOUR_PLACES_START';
export const HOME_POST_YOUR_PLACES_SUCCESS = 'HOME_POST_YOUR_PLACES_SUCCESS';
export const HOME_POST_YOUR_PLACES_FAIL = 'HOME_POST_YOUR_PLACES_FAIL';
export const HOME_GET_YOUR_PLACES_START = 'HOME_GET_YOUR_PLACES_START';
export const HOME_GET_YOUR_CUISINES_START = 'HOME_GET_YOUR_CUISINES_START';
export const HOME_GET_YOUR_PLACES_SUCCESS = 'HOME_GET_YOUR_PLACES_SUCCESS';
export const HOME_GET_YOUR_CUISINES_SUCCESS = 'HOME_GET_YOUR_CUISINES_SUCCESS';
export const HOME_GET_YOUR_PLACES_FAIL = 'HOME_GET_YOUR_PLACES_FAIL';
export const HOME_GET_YOUR_CUISINES_FAIL = 'HOME_GET_YOUR_CUISINES_FAIL';
export const HOME_LOGOUT = 'HOME_LOGOUT';

// Layout
export const LAYOUT_HANDLE_SCROLL = 'LAYOUT_HANDLE_SCROLL';

// ResPage
export const GET_ITEMS_START = 'GET_ITEMS_START';
export const GET_ITEMS_SUCCESS = 'GET_ITEMS_SUCCESS';
export const GET_ITEMS_FAIL = 'GET_ITEMS_FAIL';
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS';
export const POST_ITEM_FAIL = 'POST_ITEM_FAIL';
export const POST_VOTE_SUCCESS = 'POST_VOTE_SUCCESS';
export const POST_VOTE_FAIL = 'POST_VOTE_FAIL';

// Add to homescreen
export const BEFORE_INSTALL_PROMPT = 'BEFORE_INSTALL_PROMPT';
export const CLEAR_DEFERRED_PROMPT = 'CLEAR_DEFERRED_PROMPT';
