// Restaurants
export const RESTAURANT_FOOD_CHANGE = 'FOOD_CHANGE'
export const RESTAURANT_LOCATION_CHANGE = 'LOCATION_CHANGE'
export const RESTAURANT_SEARCH_START = 'SEARCH_START'
export const RESTAURANT_SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const RESTAURANT_SEARCH_FAIL = 'SEARCH_FAIL'

// Auth
export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
